title: "Balaprasanth Ramisetty"
description: "Data Engineer | Azure Databricks | ADF | Spark | Power BI"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "air"

author:
  name: "Balaprasanth Ramisetty"
  avatar: ""   # optional later (put image URL)
  location: "Alpharetta, GA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/balaprasanth-ramisetty"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:balaprasanthr@gmail.com"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      toc: false

markdown: kramdown
